// This file is generated by Slice Machine. Update with care!

import ImageWithCaption from './ImageWithCaption';
import Quote from './Quote';
import Text from './Text';
import Video from './Video';

export {
	ImageWithCaption,
	Quote,
	Text,
	Video,
};

export const components = {
	image_with_caption: ImageWithCaption,
	quote: Quote,
	text: Text,
	video: Video,
};
